---
# This playbook configures a single-instance SOF-ELK(R) system

- name: Run all preload steps required for a SOF-ELK system
  hosts: all
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: "Get current git branch"
      command: "git rev-parse --abbrev-ref HEAD"
      args:
        chdir: "{{ playbook_dir }}"
      register: git_branch_result
      check_mode: no
      delegate_to: 127.0.0.1
    - set_fact:
        git_branch: "{{ git_branch_result.stdout }}"


  roles:
    - elastic_repo
    - sof-elk_base
    - elasticsearch
    - cerebro
    - logstash
    - filebeat
    - kibana
    - elastalert
    - domain_stats
    - freq
    - aws-cli
    - azure-cli
    - gcp-cli
    - powershell

    - sof-elk_finalize
